version: '3.8'

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - 3030:3030